### ISSUE TITLE
Type of file mismatch when switching between windows

### ISSUE THREAD

**Issue by Terramora** [Tishka17/aiogram_dialog#123]
```
Traceback (most recent call last):
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram_dialog\dialog.py", line 154, in _callback_handler
    await self.show(dialog_manager)
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram_dialog\dialog.py", line 124, in show
    message = await manager.show(new_message)
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram_dialog\manager\manager.py", line 192, in show
    res = await show_message(self.event.bot, new_message, old_message)
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram_dialog\utils.py", line 139, in show_message
    return await edit_message(bot, new_message, old_message)
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram_dialog\utils.py", line 165, in edit_message
    return await edit_media(bot, new_message, old_message)
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram_dialog\utils.py", line 207, in edit_media
    return await bot.edit_message_media(
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram\bot\bot.py", line 2743, in edit_message_media
    result = await self.request(api.Methods.EDIT_MESSAGE_MEDIA, payload, files)
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram\bot\base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "C:\Users\Terramora.CNV\Desktop\SberMarket\channel_bot\venv\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TypeOfFileMismatch: Type of file mismatch
```
[Code](https://pastebin.com/5yTpQCbL)
When switching between `Window` with matching messages and files, risen `aiogram.utils.exceptions.TypeOfFileMismatch: Type of file mismatch`.
But if `content_type == photo`  inline keyboard is deleted for message and bot wait new messages. 
![image](https://user-images.githubusercontent.com/40336791/151718616-c5f19a18-5a92-486f-88f7-9c58740adb21.png)
If delete messages before switching `Window `error don't risen.

**Comment by Tishka17** [comment]
looks like missed `type=` param when updating message woth media
