### ISSUE TITLE
Raise an exception [UnknownIntent]

### ISSUE THREAD

**Issue by diliks** [Tishka17/aiogram_dialog#168]
**There is a problem with:  `registry = DialogRegistry(dp)`
As we launch the bot, and as soon as we are clicking on any inline-button an issue arises:** 

```
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/webhook/aiohttp_server.py", line 128, in _background_feed_update
    result = await self.dispatcher.feed_raw_update(bot=bot, update=update, **self.data)
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 167, in feed_raw_update
    return await self.feed_update(bot=bot, update=parsed_update, **kwargs)
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 135, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 24, in __call__
    return await handler(event, data)
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 212, in trigger
    return await wrapped_inner(event, kwargs)
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 244, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 129, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/venv/lib/python3.10/site-packages/aiogram_dialog/context/intent_filter.py", line 143, in process_callback_query
    await self._load_context(
  File "/venv/lib/python3.10/site-packages/aiogram_dialog/context/intent_filter.py", line 71, in _load_context
    context = await proxy.load_context(intent_id)
  File "/venv/lib/python3.10/site-packages/aiogram_dialog/context/storage.py", line 29, in load_context
    raise UnknownIntent(
aiogram_dialog.exceptions.UnknownIntent: Context not found for intent id: 
```
**MRE**
```
import logging

from aiogram import Bot, Dispatcher, Router, types
from aiogram.utils.keyboard import InlineKeyboardBuilder, InlineKeyboardButton
from aiogram.dispatcher.webhook.aiohttp_server import SimpleRequestHandler, setup_application
from aiogram_dialog import DialogRegistry
from aiohttp import web


# Config

BOT_TOKEN = "Bot:Token"

WEBHOOK_URL = "https://your.domain/bot_aiogram"
WEBHOOK_PATH = "/bot_aiogram"

WEBAPP_HOST = "localhost"
WEBAPP_PORT = 4777


# Handler

router = Router()


@router.message(content_types=types.ContentType.TEXT)
async def handle_msg(message: types.Message):
    builder = InlineKeyboardBuilder()
    builder.add(InlineKeyboardButton(text="text_callback", callback_data="some_callback"))
    await message.answer(message.text, reply_markup=builder.as_markup())


@router.callback_query(text="some_callback")
async def handle_callback(callback: types.CallbackQuery):
    print(callback)

# Main


async def on_startup(dispatcher: Dispatcher, bot: Bot):
    await bot.set_webhook(WEBHOOK_URL)


async def on_shutdown(dispatcher: Dispatcher, bot: Bot):
    await bot.delete_webhook()


def configure_app(dp, bot) -> web.Application:
    app = web.Application()
    SimpleRequestHandler(dispatcher=dp, bot=bot).register(app, path=WEBHOOK_PATH)
    setup_application(app, dp, bot=bot)
    return app


def main():
    logging.basicConfig(level=logging.DEBUG)
    bot = Bot(token=BOT_TOKEN, parse_mode="html")
    dp = Dispatcher()

    dp.include_router(router=router)

    # Registering Dialog
    registry = DialogRegistry(dp)

    dp.startup.register(on_startup)
    dp.shutdown.register(on_shutdown)
    app = configure_app(dp, bot)
    web.run_app(app, host=WEBAPP_HOST, port=WEBAPP_PORT)


if __name__ == '__main__':
    main()
```
**Requirements**: 
```
aiogram==3.0.0b3
aiohttp==3.8.1
aiogram-dialog==2.0.0b7
```

**Comment by Tishka17** [comment]
see 2.0.0b8
