### ISSUE TITLE
Bug: cannot set default value on start dialog in checkbox widget

### ISSUE THREAD

**Issue by abrikk** [Tishka17/aiogram_dialog#169]
### The error:
````
Traceback (most recent call last):
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/venv/lib/python3.10/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/aiogram_dialog/manager/registry.py", line 77, in start_dialog
    await dialog_manager.start(state, mode=StartMode.RESET_STACK)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/aiogram_dialog/manager/manager.py", line 134, in start
    await self._start_normal(state, data)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/aiogram_dialog/manager/manager.py", line 174, in _start_normal
    await self._dialog().process_start(self, data, state)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/aiogram_dialog/dialog.py", line 106, in process_start
    await self._process_callback(self.on_start, start_data, manager)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/aiogram_dialog/dialog.py", line 110, in _process_callback
    await callback(*args, **kwargs)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/example/subdialog.py", line 27, in set_default
    await dialog_manager.dialog().find('is_fixed').set_checked(event=dialog_manager.event, checked=True)
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/aiogram_dialog/widgets/kbd/checkbox.py", line 101, in set_checked
    return await self.widget.set_checked(
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/aiogram_dialog/widgets/kbd/checkbox.py", line 85, in set_checked
    await self.on_state_changed.process_event(
  File "/home/abror/Abrik/MyProjects/libs/aiogram_dialog/aiogram_dialog/widgets/widget_event.py", line 18, in process_event
    await self.callback(event, source, manager, *args, **kwargs)
TypeError: 'str' object is not callable
````

### MRE

```
import asyncio
import logging
from typing import Any

from aiogram import Bot, Dispatcher
from aiogram.contrib.fsm_storage.memory import MemoryStorage
from aiogram.dispatcher.filters.state import StatesGroup, State
from aiogram.types import Message

from aiogram_dialog import Dialog, DialogManager, Window, DialogRegistry, ShowMode
from aiogram_dialog.manager.protocols import ManagedDialogAdapterProto
from aiogram_dialog.widgets.input import MessageInput
from aiogram_dialog.widgets.kbd import Cancel, Next, Checkbox
from aiogram_dialog.widgets.text import Const

API_TOKEN = "PLACE YOUR TOKEN HERE"


class NameSG(StatesGroup):
    input = State()
    admin = State()


async def set_default(_: Any, dialog_manager: DialogManager):
    await dialog_manager.dialog().find('is_fixed').set_checked(event=dialog_manager.event, checked=True)


async def password_handler(m: Message, _widget: ManagedDialogAdapterProto, manager: DialogManager):
    if m.text == "admin":
        manager.current_context().dialog_data["is_admin"] = True
        await manager.dialog().next()
    else:
        manager.show_mode = ShowMode.EDIT
        await m.answer("You entered a wrong password")


async def get_is_admin(dialog_manager: DialogManager, **kwargs):
    return {
        "is_admin": dialog_manager.current_context().dialog_data.get("is_admin")
    }


name_dialog = Dialog(
    Window(
        Const("Enter password to login (admin):"),
        Cancel(),
        MessageInput(func=password_handler),
        state=NameSG.input,
    ),
    Window(
        Const("Hello! Is Bug fixed?"),
        Checkbox(
            checked_text=Const("Yes ✅"),
            unchecked_text=Const("No ❌"),
            id="is_fixed",
            default=False,
            when="is_admin"
        ),
        Cancel(),
        state=NameSG.admin,
        getter=get_is_admin,
        preview_add_transitions=[Next()],  # hint for graph rendering
    ),
    on_start=set_default
)


async def main():
    # real main
    logging.basicConfig(level=logging.INFO)
    storage = MemoryStorage()
    bot = Bot(token=API_TOKEN)
    dp = Dispatcher(bot, storage=storage)
    registry = DialogRegistry(dp)
    registry.register_start_handler(NameSG.input)  # resets stack and start dialogs on /start command
    registry.register(name_dialog)

    await dp.start_polling()


if __name__ == '__main__':
    asyncio.run(main())


```

`aiogram_dialog version: 1.7.0`

**Comment by Tishka17** [comment]
see 1.8.0
