### ISSUE TITLE
`TypeError: argument of type 'NoneType' is not iterable`

### ISSUE THREAD

**Issue by andrew000** [Tishka17/aiogram_dialog#174]
## How to reproduce the error:
Use `/test` in supergroup chat to get bot's message with url inline button. Then reply to this message with any text. So you will get an error `TypeError: argument of type 'NoneType' is not iterable`

## MRE: 
```py
class MySG(StatesGroup):
    main = State()


main_window = Window(
    Const("Hello, unknown person"),
    Button(Const("Useless button"), id="nothing"),
    state=MySG.main,
)
dialog = Dialog(main_window)
registry.register(dialog)


@dp.message_handler(commands=["test"])
async def start(msg: Message, dialog_manager: DialogManager):
    if msg.chat.type == "private":
        await dialog_manager.start(MySG.main, mode=StartMode.RESET_STACK)
    else:
        await msg.answer(
            "Inline Button with Google.com url",
            reply_markup=InlineKeyboardMarkup(
                inline_keyboard=[
                    [
                        InlineKeyboardButton(text="Google", url="https://google.com"),
                    ]
                ]
            ),
        )
```

## ERROR:
```
Traceback (most recent call last):
File "/root/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "/root/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 100, in notify
    await self.dispatcher.middleware.trigger(f"pre_process_{self.middleware_key}", args + (data,))
  File "/root/.local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares.py", line 53, in trigger
    await app.trigger(action, args)
  File "/root/.local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares.py", line 106, in trigger
    await handler(*args)
  File "/root/.local/lib/python3.9/site-packages/aiogram_dialog/context/intent_filter.py", line 111, in on_pre_process_message
    intent_id, callback_data = remove_indent_id(button.callback_data)
  File "/root/.local/lib/python3.9/site-packages/aiogram_dialog/utils.py", line 77, in remove_indent_id
    if CB_SEP in callback_data:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Tishka17** [comment]
see 1.8.0

**Comment by prepwork** [comment]
> see 1.8.0

Bug is still present in 2.0.0b17 when you try to open game:

```
File "C:\...\aiogram_dialog\utils.py", line 79, in remove_indent_id
    if CB_SEP in callback_data:
TypeError: argument of type 'NoneType' is not iterable
```

Reproduce:
1. Run sample code.
2. Send `/play` command
3. Click Play button

```python
from aiogram import Bot, Dispatcher, F
from aiogram.fsm.storage.memory import MemoryStorage
from aiogram.types import CallbackQuery, Message
from aiogram_dialog import DialogRegistry

BOT_TOKEN = ""
GAME_SHORT_NAME = "test_game"


async def cmd_play(m: Message):
    await m.answer_game(game_short_name=GAME_SHORT_NAME)


async def open_game(c: CallbackQuery):
    await c.answer(url="https://127.0.0.1:8000")


def main():
    bot = Bot(BOT_TOKEN)

    storage = MemoryStorage()
    dp = Dispatcher(storage=storage)

    dp.message.register(cmd_play, F.text == "/play")
    dp.callback_query.register(open_game, F.game_short_name == GAME_SHORT_NAME)

    registry = DialogRegistry()
    registry.setup_dp(dp)

    dp.run_polling(bot)


if __name__ == '__main__':
    main()
```
