### ISSUE TITLE
An error when handling UknownIntentError

### ISSUE THREAD

**Issue by Sonotoki-da** [Tishka17/aiogram_dialog#210]
### the Problem
Steps to reproduce the problem we are facing:
1. Launch the bot with **the MRE** I've attached to this issue (See below). Don't forget to set your bot token.
2. Do nothing after the launch, and just relaunch the bot again.
3. Press a button in a dialog left in old session of the bot. It will launch a new dialog without issues.
4. Now, press the oldest button again in the current session.
### My specs:
Python: `Python 3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0] on linux`
aiogram: `3.0.0b5`
aiogram_dialog: `2.0.0b12`
### an Output:
```
(venv) sohro@ubuntu-4gb-hel1-1:~/vscodeserver/telegrambot$  cd /home/sohro/vscodeserver/telegrambot ; /usr/bin/env /home/sohro/vscodeserver/telegrambot/venv/bin/python /home/sohro/.local/share/code-server/extensions/ms-python.python-2022.16.1-universal/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 35887 -- /home/sohro/vscodeserver/telegrambot/tests.py 
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @testbot id=5710103350 - 'testbot'
INFO:aiogram.event:Update id=811675420 is handled. Duration 242 ms by bot id=5710103350
INFO:aiogram.event:Update id=811675421 is not handled. Duration 3 ms by bot id=5710103350
ERROR:aiogram.event:Cause exception while process update id=811675421 by bot id=5710103350
KeyError: 'aiogd_context'
Traceback (most recent call last):
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 34, in __call__
    return await handler(event, data)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 111, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 260, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram_dialog/context/intent_middleware.py", line 149, in process_callback_query
    await self._load_context(event, intent_id, DEFAULT_STACK_ID, data)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram_dialog/context/intent_middleware.py", line 74, in _load_context
    context = await proxy.load_context(intent_id)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram_dialog/context/storage.py", line 35, in load_context
    raise UnknownIntent(
aiogram_dialog.api.exceptions.UnknownIntent: Context not found for intent id: 1aX6y4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram_dialog/context/intent_middleware.py", line 213, in __call__
    context = await proxy.load_context(stack.last_intent_id())
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram_dialog/context/storage.py", line 35, in load_context
    raise UnknownIntent(
aiogram_dialog.api.exceptions.UnknownIntent: Context not found for intent id: pvV3H2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 293, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 142, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 29, in __call__
    response = await self.router.propagate_event(
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/sohro/vscodeserver/telegrambot/venv/lib/python3.10/site-packages/aiogram_dialog/context/intent_middleware.py", line 220, in __call__
    context = data.pop(CONTEXT_KEY)
KeyError: 'aiogd_context'
```

### a MRE:
```python
import asyncio
import logging
import os.path

from aiogram import Bot, Dispatcher, F
from aiogram.dispatcher.event.bases import UNHANDLED
from aiogram.fsm.state import State, StatesGroup
from aiogram.fsm.storage.memory import MemoryStorage
from aiogram.types import Message
from aiogram_dialog import Dialog, DialogManager, DialogRegistry, StartMode, Window
from aiogram_dialog.api.exceptions import UnknownIntent
from aiogram_dialog.widgets.kbd import Button
from aiogram_dialog.widgets.text import Const

src_dir = os.path.normpath(os.path.join(__file__, os.path.pardir))

API_TOKEN = "BOT_TOKEN"


class DialogSG(StatesGroup):
    main = State()


dialog = Dialog(
    Window(
        Const("Handling the UnkownIntentError case!"),
        Button(Const("Button"), "button"),
        state=DialogSG.main,
    ),
)


async def start(message: Message, dialog_manager: DialogManager):
    await dialog_manager.start(DialogSG.main, mode=StartMode.RESET_STACK)


async def error_handler(event, dialog_manager: DialogManager):
    """An example of handling the UnknownIntent error, and starting a new dialog"""
    if isinstance(event.exception, UnknownIntent):
        await dialog_manager.start(DialogSG.main, mode=StartMode.RESET_STACK)
    else:
        return UNHANDLED


async def main():
    logging.basicConfig(level=logging.INFO)

    bot = Bot(token=API_TOKEN)
    dp = Dispatcher(storage=MemoryStorage())
    dp.message.register(start, F.text == "/start")
    dp.errors.register(error_handler)

    registry = DialogRegistry(dp)
    registry.register(dialog)

    await dp.start_polling(bot)


if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by myown-del** [comment]
I managed to reproduce the issue.
Can add that if you patch `aiogram_dialog.manager.manager` module's `_get_fake_user` method of class `ManagerImpl` to:
```
    def _get_fake_user(self, user_id: Optional[int] = None) -> User:
        """Get User if we have info about him or FakeUser instead."""
        if isinstance(self.event, ErrorEvent):
            if self.event.update.callback_query:
                current_user = self.event.update.callback_query.from_user
            else:
                current_user = self.event.update.message.from_user
        else:
            current_user = self.event.from_user
        if user_id in (None, current_user.id):
            return current_user
        return FakeUser(id=user_id, is_bot=False, first_name="")
```
And start new dialog with `state=StartMode.NEW_STACK`, that seems to fix the issue, but not completely. `TextInput` widget won't receive any user-entered text.
