### ISSUE TITLE
AttributeError: 'ManagerImpl' object has no attribute 'data'

### ISSUE THREAD

**Issue by samich80** [Tishka17/aiogram_dialog#330]
aiofiles           23.1.0
aiogram            3.1.1
aiogram-dialog     2.0.0

async def on_start(self, manager: DialogManager):
    telegram_id = manager.event.from_user.id
    repo: Repo = manager.data["repo"]           #ошибка

AttributeError: 'ManagerImpl' object has no attribute 'data'
Traceback (most recent call last):
  File "D:\projects\mfcs\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
..........  

  File "D:\projects\mfcs\.venv\Lib\site-packages\aiogram_dialog\dialog.py", line 100, in _process_callback
    await callback(*args, **kwargs)
  File "D:\projects\mfcs\app\bot\dialogs\main_menu.py", line 12, in on_start
    repo: Repo = manager.data["repo"]
                 ^^^^^^^^^^^^
AttributeError: 'ManagerImpl' object has no attribute 'data'

**Comment by Tishka17** [comment]
it is called `middleware_data` since version 2.0
