### ISSUE TITLE
DynamicMedia error

### ISSUE THREAD

**Issue by alexey-fedchishyn** [Tishka17/aiogram_dialog#427]
Hello!
It appears when a window with a DynamicMedia is opening.

Traceback:
`Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\fsm\middleware.py", line 41, in __call__
    return await handler(event, data)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\manager\manager_middleware.py", line 77, in __call__
    return await handler(event, data)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\context\intent_middleware.py", line 186, in process_callback_query
    return await handler(event, data)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\manager\manager_middleware.py", line 77, in __call__
    return await handler(event, data)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\manager\manager_middleware.py", line 52, in __call__
    return await handler(event, data)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\context\intent_middleware.py", line 198, in context_saver_middleware
    result = await handler(event, data)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\dialog.py", line 148, in _callback_handler
    await dialog_manager.show()
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\manager\manager.py", line 314, in show
    sent_message = await self.message_manager.show_message(
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\manager\message_manager.py", line 182, in show_message
    await self.send_message(bot, new_message),
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\manager\message_manager.py", line 347, in send_message
    return await self.send_media(bot, new_message)
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\manager\message_manager.py", line 374, in send_media
    await self.get_media_source(new_message.media, bot),
  File "C:\Users\HP\PycharmProjects\GuardBot\.venv\lib\site-packages\aiogram_dialog\manager\message_manager.py", line 89, in get_media_source
    return media.file_id.file_id
AttributeError: 'str' object has no attribute 'file_id'`

The reason is obvious. So I hope you will fix it soon :)

**Comment by Tishka17** [comment]
What is your code?

**Comment by alexey-fedchishyn** [comment]
Window:

`def edit_pet_window():
    return Window(
        DynamicMedia('pet_image', when=when.is_pet_image),
        Format('{pet_format}\n'),
        Format('{windows[edit_pet]}'),
        keyboards.pet_action_kb(),
        MessageInput(func=on_input_pet_photo, content_types=ContentType.PHOTO),
        state=MyPets.edit,
        getter=getters.get_pet
    )`

Getter:

`if file_id:
    pet_image = MediaAttachment(ContentType.PHOTO, file_id=file_id)
data = {'pet_format': f'{pet.animal} {pet.name} ({pet.color} {pet.breed})', 'pet_image': pet_image}
data = get_data(data, lang_code, middleware_data.get('translations'), ctx)
return data`

**Comment by alexey-fedchishyn** [comment]
![media_attachment_02](https://github.com/user-attachments/assets/d88d7033-5cfc-46a7-8ff8-3667bcc3e870)
![media_attachment_03](https://github.com/user-attachments/assets/0d892414-e8fa-4956-9408-275a3b8e3afa)

**Comment by Tishka17** [comment]
What is file_id here? Looks like you are passing string there

**Comment by alexey-fedchishyn** [comment]
OMG, I thought file_id is a file_id. But it's an object. Sorry, my bad...

**Comment by Tishka17** [comment]
By some reason telegram decided to have 2 IDs, so we have to store both for different cases

**Comment by alexey-fedchishyn** [comment]
Yes, it's a little bit confusing
