### ISSUE TITLE
Media Type Attribute Error in Message Manager

### ISSUE THREAD

**Issue by Latand** [Tishka17/aiogram_dialog#446]
The message manager encounters an AttributeError when trying to access the type attribute of the media field in NewMessage. This error occurs because the media field is sometimes being set as a string instead of the expected MediaAttachment type. The issue became apparent after the recent commit ([5552ee2](https://github.com/Tishka17/aiogram_dialog/commit/5552ee2acf958df25b7e32f92f1ea177a40b2310)) that added voice message handling checks.

logs:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiogram_dialog/dialog.py", line 155, in *callback*handler
    await dialog_manager.show()
  File "/usr/local/lib/python3.11/site-packages/aiogram_dialog/manager/manager.py", line 372, in show
    sent_message = await self.message_manager.show_message(
  File "/usr/local/lib/python3.11/site-packages/aiogram_dialog/manager/message_manager.py", line 198, in show_message
    if not self._can_edit(new_message, old_message):
  File "/usr/local/lib/python3.11/site-packages/aiogram_dialog/manager/message_manager.py", line 154, in *can*edit
    if self.had_voice(old_message) or self.need_voice(new_message):
  File "/usr/local/lib/python3.11/site-packages/aiogram_dialog/manager/message_manager.py", line 126, in need_voice
    and new_message.media.type == ContentType.VOICE
AttributeError: 'str' object has no attribute 'type'
``

**Comment by Tishka17** [comment]
it is very strange because 
```python
media: Optional[MediaAttachment] = None
```

https://github.com/Tishka17/aiogram_dialog/blob/develop/src/aiogram_dialog/api/entities/new_message.py
