### ISSUE TITLE
Calendar does not support RedisStorage2

### ISSUE THREAD

**Issue by aobcvr** [Tishka17/aiogram_dialog#62]
```
# /app/test.py
from aiogram import Bot, Dispatcher, executor
from aiogram.contrib.fsm_storage.redis import RedisStorage2
from aiogram.dispatcher.filters.state import StatesGroup, State
from aiogram.types import Message

from aiogram_dialog import Window, Dialog, DialogRegistry, DialogManager, StartMode
from aiogram_dialog.widgets.kbd import Button
from aiogram_dialog.widgets.text import Const
from datetime import date

from aiogram.types import CallbackQuery

from aiogram_dialog import DialogManager
from aiogram_dialog.widgets.kbd import Calendar


async def on_date_selected(c: CallbackQuery, widget, manager: DialogManager, selected_date: date):
    await c.answer(str(selected_date))


storage = RedisStorage2('redis')
bot = Bot(token='TOKEN')
dp = Dispatcher(bot, storage=storage)
registry = DialogRegistry(dp)


class MySG(StatesGroup):
    main = State()


main_window = Window(
    Const("Hello, unknown person"),
    Calendar(id='calendar', on_click=on_date_selected),
    state=MySG.main,
)
dialog = Dialog(main_window)
registry.register(dialog)


@dp.message_handler(commands=["start"])
async def start(m: Message, dialog_manager: DialogManager):
    await dialog_manager.start(MySG.main, mode=StartMode.RESET_STACK)


if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=True)
```

```
sid@83cfd5fbfc97:/app$ python test.py 
Updates were skipped successfully.
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /home/sid/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=TypeError('Object of type date is not JSON serializable')>
Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 129, in notify
    await self.dispatcher.middleware.trigger(f"post_process_{self.middleware_key}",
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares.py", line 53, in trigger
    await app.trigger(action, args)
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares.py", line 106, in trigger
    await handler(*args)
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram_dialog/context/intent_filter.py", line 66, in on_post_process_message
    await proxy.save_context(data.pop(CONTEXT_KEY))
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram_dialog/context/storage.py", line 45, in save_context
    await self.storage.set_data(
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram/contrib/fsm_storage/redis.py", line 307, in set_data
    await redis.set(key, json.dumps(data), expire=self._data_ttl)
  File "/home/sid/.local/lib/python3.9/site-packages/aiogram/utils/json.py", line 43, in dumps
    return json.dumps(data, ensure_ascii=False)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
```

**Comment by bralbral** [comment]
There is no `date` type in json. It is not RedisStorage2 issue. Probably need convert datetime type into `string` or `timestamp ` when serialializing?
