### ISSUE TITLE
Index Error in dialogs.py ! next ! method

### ISSUE THREAD

**Issue by Salz0** [Tishka17/aiogram_dialog#74]
```py
    async def next(self, manager: DialogManager):
        if not manager.current_context():
            raise ValueError("No intent")
        print(self.states)
        print(self.states.index(manager.current_context().state))
        print(self.states.index(manager.current_context().state) + 1)
        new_state = self.states[self.states.index(manager.current_context().state) + 1]
        await self.switch_to(new_state, manager)
```
When I'm pressing scroll arrows -> throwing an index error.
Here is the output with the additional `print statements`

```py
[<State 'Link[0.0.1:1'>, <State 'Link[0.0.1:2'>]
1
2
Task exception was never retrieved
future: <Task finished name='Task-28' coro=<Dispatcher._process_polling_updates() done, defined at /Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/mac/Documents/PycharmProjects/CustomBot/main.py", line 321, in callback
    await dialog_manager.dialog().next(dialog_manager)
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram_dialog/dialog.py", line 78, in next
    new_state = self.states[self.states.index(manager.current_context().state) + 1]
IndexError: list index out of range
```

**Comment by Salz0** [comment]
The list should account for the 0th index

**Comment by Salz0** [comment]
Found the issue in my own code.

**Comment by Salz0** [comment]
```py
Task exception was never retrieved
future: <Task finished name='Task-30' coro=<Dispatcher._process_polling_updates() done, defined at /Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 286, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/Users/mac/Documents/PycharmProjects/CustomBot/main.py", line 323, in callback
    await dialog_manager.dialog().next(dialog_manager)
  File "/Users/mac/Library/Caches/pypoetry/virtualenvs/custombot-VvSOzSsp-py3.9/lib/python3.9/site-packages/aiogram_dialog/dialog.py", line 78, in next
    new_state = self.states[self.states.index(manager.current_context().state) + 1]
IndexError: list index out of range
[<State 'Link[0.0.1:1'>, <State 'Link[0.0.1:2'>]
1
2
```
I have a scrolling group. And this is what I get from pressing the arrow to scroll further (From page `1`)

**Comment by Salz0** [comment]
What should I execute to scroll further?

**Comment by Salz0** [comment]
It tries to move states when it should just scroll and not create any callback

**Comment by Salz0** [comment]
```py
async def callback(callback_query: types.CallbackQuery, dialog_manager: DialogManager):
    await bot.answer_callback_query(callback_query.id)
    userID = callback_query.from_user.id
    logger.info(f"{callback=}")
    # await go_next(callback_query, None, manager=dialog_manager)
    logger.debug(f"{dialog_manager.current_context().state=}")
    if callback_query.data.startswith("scroll"):
        ...
    # await dialog_manager.start(TmpState.st, mode=StartMode.RESET_STACK)
    await dialog_manager.dialog().next(dialog_manager)
```
What can I do to scroll and not move states?

**Comment by Tishka17** [comment]
It looks that you are calling on `next` the last window in dialog. Where do expect it to switch?
Please, share you dialog definition

**Comment by Salz0** [comment]
The code is very sophisticated, I will try to comment on some parts

```py
async def register_dialogs(dp):

    states_registry = []
    registry = DialogRegistry(dp)
    for i in MESSAGE:
        if all([i.startswith("Link["), i.endswith("]")]):
            windows = []

            link_length = len(i)
            states = generate_states_of_a_unique_group(
                group_prefix=i.lstrip("[").rstrip("]"), amount_of_states=link_length
            )
            for ii, item in enumerate(MESSAGE[i]):
                order_id_of_list = item.removeprefix("List[").rstrip("]")
                state_ = states[ii]
                states_registry.append(
                    {"key": f"CommandState[{order_id_of_list}]", "value": state_}
                )
                buttons = await buttons_creator(
                    MESSAGE[item],
                    _class=MESSAGE[f"Command[{order_id_of_list}]"],
                    randomness=MESSAGE[f"{item}Randomness"],
                )
                try:
                    if ii == 0:
                        windows.append(
                            Window(
                                Const(MESSAGE[f"Response[{order_id_of_list}]"]),
                                ScrollingGroup(
                                    *buttons,
                                    width=2,
                                    height=3,
                                    id=f"scroll_{order_id_of_list}",
                                ),
                                state=state_,
                            )
                        )
                    else:
                        windows.append(
                            Window(
                                Const(MESSAGE[f"Response[{order_id_of_list}]"]),
                                Back(Const("❌Back"), on_click=go_back),
                                ScrollingGroup(
                                    *buttons,
                                    width=2,
                                    height=3,
                                    id=f"scroll_{order_id_of_list}",
                                ),
                                state=state_,
                            )
                        )
                        logger.info(f"{state_=}")
                except KeyError as e:
                    logger.warning(f"Please, create a {e.args[0]} key")
            logger.debug(f"{windows=}")
            registry.register(Dialog(*windows))
            logger.info(f"Registered Dialog of {i}")

    for ii in states_registry:
        MESSAGE[ii["key"]] = ii["value"]

    states_tmp = {}

    for iii in MESSAGE:
        if all([iii.startswith("Command["), iii.endswith("]")]):
            command = MESSAGE.get(iii, False)
            if not command:
                break
            else:
                index = iii.removeprefix("Command[").rstrip("]")
                number = int(iii.split(".")[1])
                if 8 <= number:
                    state_ = MESSAGE.get(f"CommandState[{index}]", False)
                    states_tmp[command] = state_
                    if state_:

                        # this is done because if we register the same function more than once,
                        # the function will be overwritten.

                        # Here we access predefined functions from "abstraction_costyl.py" to avoid
                        # Overwriting. Another (general) solution is highly desirable.
                        import importlib
                        module = importlib.import_module("abstraction_costyl")
                        function_ = getattr(module, f"command{number}_")
                        dp.register_message_handler(
                            function_(state=state_),
                            commands=[command],
                            regexp=None,
                            content_types=None,
                            state="*",
                            run_task=None,
                        )

                        logger.debug(f"Registered command {command}")
```

**Comment by Salz0** [comment]
> It looks that you are calling on `next` the last window in dialog. Where do expect it to switch?
> Please, share you dialog definition

It tries to switch states when I press the Scroll arrows

**Comment by Tishka17** [comment]
what the hell is this? please stop generating windows and dialogs.
you can use single window and change data inside it on clicks. Another variant is to use subdialogs. 

what is the purpose of all this code?

**Comment by Salz0** [comment]
> what the hell is this? please stop generating windows and dialogs.
> you can use single window and change data inside it on clicks. Another variant is to use subdialogs.
> 
> what is the purpose of all this code?

I hope you are not irritated or confused by it. 

the purpose is to generate any amount of dialogs, who follow the same structure.

Creating something like a small wiki, where we generate a page, which is linked by many others.

Btw, do you know russian? Maybe I'll explain it better

**Comment by Tishka17** [comment]
Let's continue diacussion in telegram: https://t.me/aiogram_dialog
